import assert from 'node:assert/strict';
import { parseQuery, removeToken, suggest, tokenLabel } from './searchQuery.js';
const keys = new Set(['born', 'faction']);
let r = parseQuery('wolves kind:npc -tag:dead born>=300 faction:"Silver Court" edited:7d', keys);
assert.equal(r.words, 'wolves');
assert.equal(r.facets.kind, 'npc'); assert.equal(r.facets.not_tag, 'dead');
assert.deepEqual(r.facets.props, [{ field: 'born', op: '>=', value: '300' }, { field: 'faction', op: ':', value: 'Silver Court' }]);
assert.ok(r.facets.edited_after > 0);
r = parseQuery('see http://x.io time:12 kind:', keys);
assert.equal(r.tokens.length, 0); assert.equal(r.words, 'see http://x.io time:12 kind:');
r = parseQuery('-born>5 -faction:x kind:a kind:b tag:#elf', keys);
assert.equal(r.words, '-born>5'); assert.equal(r.facets.kind, 'a,b'); assert.equal(r.facets.tag, 'elf');
assert.deepEqual(r.facets.props, [{ field: 'faction', op: '!=', value: 'x' }]);
r = parseQuery('a kind:npc b', keys);
assert.equal(removeToken('a kind:npc b', r.tokens[0]), 'a b');
assert.equal(tokenLabel(parseQuery('-tag:dead').tokens[0]), '−tag:dead');
assert.equal(suggest('ki', { propKeys: ['born'] }).items[0].insert, 'kind:');
assert.equal(suggest('x kind:n', { kinds: ['npc', 'place'] }).items[0].insert, 'kind:npc ');
assert.equal(suggest('kind:npc ', {}), null);
console.log('parser ok');
