import assert from 'node:assert/strict';
import { clampRect, placeNear, normalizePreviews, withPreview, initialKeys, keysReduce, previewTarget, MIN_W, MIN_H } from './atlasPreviewLogic.js';
import { pageHeadings } from './atlasPage.js';
const stage = { w: 1000, h: 700 };
assert.deepEqual(clampRect({ x: -50, y: 900, w: 320, h: 340 }, stage), { x: 0, y: 360, w: 320, h: 340 });
assert.equal(clampRect({ x: 0, y: 0, w: 10, h: 10 }, stage).w, MIN_W);
assert.equal(clampRect({ x: 0, y: 0, w: 10, h: 10 }, stage).h, MIN_H);
assert.equal(clampRect({ x: NaN, y: NaN, w: NaN, h: NaN }, stage).w, 320);
assert.equal(clampRect({ x: 0, y: 0, w: 5000, h: 5000 }, stage).w, 1000);
const tiny = clampRect({ x: 50, y: 50, w: 320, h: 340 }, { w: 100, h: 100 });
assert.equal(tiny.x, 0); assert.equal(tiny.y, 0);
assert.equal(placeNear(100, 300, stage).x, 130);
const flipped = placeNear(900, 300, stage);
assert.equal(flipped.x, 900 - 30 - 320);
assert.ok(flipped.y >= 0 && flipped.y + flipped.h <= 700);
const list = [{ pin_id: 'a', x: -5, y: 5, w: 300, h: 300 }, { pin_id: 'a', x: 1, y: 1, w: 300, h: 300 }, { pin_id: 'gone', x: 1, y: 1, w: 300, h: 300 }, null];
const n = normalizePreviews(list, ['a', 'b'], stage);
assert.equal(n.length, 1); assert.equal(n[0].x, 0);
const ids = Array.from({ length: 20 }, (_, i) => 'p' + i);
assert.equal(normalizePreviews(ids.map((id) => ({ pin_id: id, x: 0, y: 0, w: 300, h: 300 })), ids, stage).length, 8);
let l = withPreview([], 'a', { x: 1.4, y: 2.6, w: 300, h: 300 });
assert.deepEqual(l[0], { pin_id: 'a', x: 1, y: 3, w: 300, h: 300 });
l = withPreview(l, 'a', { x: 9, y: 9, w: 300, h: 300 }); assert.equal(l.length, 1); assert.equal(l[0].x, 9);
assert.equal(withPreview(l, 'a', null).length, 0);
let many = []; for (let i = 0; i < 12; i++) many = withPreview(many, 'p' + i, { x: 0, y: 0, w: 300, h: 300 });
assert.equal(many.length, 8); assert.equal(many.at(-1).pin_id, 'p11');
let s = initialKeys();
s = keysReduce(s, { type: 'hover', id: 'a' }); assert.equal(previewTarget(s), null);
s = keysReduce(s, { type: 'mod', on: true }); assert.equal(previewTarget(s), 'a');
s = keysReduce(s, { type: 'card', id: 'a' }); s = keysReduce(s, { type: 'hover', id: null }); assert.equal(previewTarget(s), 'a');
s = keysReduce(s, { type: 'card', id: null }); assert.equal(previewTarget(s), null);
s = keysReduce(s, { type: 'hover', id: 'b' }); assert.equal(previewTarget(s), 'b');
s = keysReduce(s, { type: 'mod', on: false }); assert.equal(previewTarget(s), null);
s = keysReduce(keysReduce(s, { type: 'mod', on: true }), { type: 'blur' }); assert.deepEqual(s, initialKeys());
assert.equal(keysReduce(s, { type: 'hover', id: null }), s);
assert.deepEqual(pageHeadings('# A\ntext\n```\n# no\n```\n## B ##\n#### deep'), ['A', 'B']);
console.log('preview logic ok');
